# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.setWindowIcon(QtGui.QIcon("icon/icon.png"))
        TabWidget.resize(410, 440)
        TabWidget.setFixedSize(410, 440)
        TabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        TabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        TabWidget.setIconSize(QtCore.QSize(16, 16))
        TabWidget.setTabsClosable(False)
        TabWidget.setTabBarAutoHide(False)
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.serverFrame = QtWidgets.QFrame(self.mainTab)
        self.serverFrame.setGeometry(QtCore.QRect(0, 0, 400, 80))
        self.serverFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.serverFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.serverFrame.setLineWidth(1)
        self.serverFrame.setMidLineWidth(0)
        self.serverFrame.setObjectName("serverFrame")
        self.serverAddressLabel = QtWidgets.QLabel(self.serverFrame)
        self.serverAddressLabel.setGeometry(QtCore.QRect(90, 40, 291, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.serverAddressLabel.setFont(font)
        self.serverAddressLabel.setTextFormat(QtCore.Qt.AutoText)
        self.serverAddressLabel.setObjectName("serverAddressLabel")
        self.serverSelectComboBox = QtWidgets.QComboBox(self.serverFrame)
        self.serverSelectComboBox.setGeometry(QtCore.QRect(90, 10, 200, 20))
        self.serverSelectComboBox.setObjectName("serverSelectComboBox")
        self.serverSelectComboBox.addItem("")
        self.serverTitleLabel = QtWidgets.QLabel(self.serverFrame)
        self.serverTitleLabel.setGeometry(QtCore.QRect(10, 10, 70, 30))
        self.serverTitleLabel.setObjectName("serverTitleLabel")
        self.serverManagePushButton = QtWidgets.QPushButton(self.serverFrame)
        self.serverManagePushButton.setGeometry(QtCore.QRect(300, 10, 80, 20))
        self.serverManagePushButton.setObjectName("serverManagePushButton")
        self.groupNameFrame = QtWidgets.QFrame(self.mainTab)
        self.groupNameFrame.setGeometry(QtCore.QRect(0, 90, 400, 50))
        self.groupNameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groupNameFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.groupNameFrame.setObjectName("groupNameFrame")
        self.groupnameTitleLabel = QtWidgets.QLabel(self.groupNameFrame)
        self.groupnameTitleLabel.setGeometry(QtCore.QRect(10, 10, 60, 30))
        self.groupnameTitleLabel.setObjectName("groupnameTitleLabel")
        self.groupnameLineEdit = QtWidgets.QLineEdit(self.groupNameFrame)
        self.groupnameLineEdit.setGeometry(QtCore.QRect(90, 10, 280, 30))
        self.groupnameLineEdit.setObjectName("groupnameLineEdit")
        self.localipFrame = QtWidgets.QFrame(self.mainTab)
        self.localipFrame.setGeometry(QtCore.QRect(0, 150, 400, 50))
        self.localipFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.localipFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.localipFrame.setObjectName("localipFrame")
        self.localipTitleLabel = QtWidgets.QLabel(self.localipFrame)
        self.localipTitleLabel.setGeometry(QtCore.QRect(10, 10, 60, 30))
        self.localipTitleLabel.setObjectName("localipTitleLabel")
        self.localipLineEdit = QtWidgets.QLineEdit(self.localipFrame)
        self.localipLineEdit.setGeometry(QtCore.QRect(90, 10, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.localipLineEdit.setFont(font)
        self.localipLineEdit.setObjectName("localipLineEdit")
        self.localipAutoCheckBox = QtWidgets.QCheckBox(self.localipFrame)
        self.localipAutoCheckBox.setGeometry(QtCore.QRect(280, 10, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.localipAutoCheckBox.setFont(font)
        self.localipAutoCheckBox.setObjectName("localipAutoCheckBox")
        self.connectionFrame = QtWidgets.QFrame(self.mainTab)
        self.connectionFrame.setGeometry(QtCore.QRect(0, 210, 400, 200))
        self.connectionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connectionFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.connectionFrame.setObjectName("connectionFrame")
        self.connectionPushButton = QtWidgets.QPushButton(self.connectionFrame)
        self.connectionPushButton.setGeometry(QtCore.QRect(310, 160, 75, 30))
        self.connectionPushButton.setObjectName("connectionPushButton")
        self.connectionMsgTextBrowser = QtWidgets.QTextBrowser(self.connectionFrame)
        self.connectionMsgTextBrowser.setGeometry(QtCore.QRect(10, 10, 380, 140))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.connectionMsgTextBrowser.setFont(font)
        self.connectionMsgTextBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.connectionMsgTextBrowser.setFrameShape(QtWidgets.QFrame.Panel)
        self.connectionMsgTextBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.connectionMsgTextBrowser.setLineWidth(1)
        self.connectionMsgTextBrowser.setObjectName("connectionMsgTextBrowser")
        TabWidget.addTab(self.mainTab, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "N2N"))
        self.serverAddressLabel.setText(_translate("TabWidget", "52.192.105.70:3000"))
        self.serverSelectComboBox.setItemText(0, _translate("TabWidget", "节点 1 : 日本 - 东京"))
        self.serverTitleLabel.setText(_translate("TabWidget", "服务器节点"))
        self.serverManagePushButton.setText(_translate("TabWidget", "管理节点"))
        self.groupnameTitleLabel.setText(_translate("TabWidget", "群组名"))
        self.groupnameLineEdit.setText(_translate("TabWidget", "GDJAY1"))
        self.localipTitleLabel.setText(_translate("TabWidget", "本机地址"))
        self.localipLineEdit.setInputMask(_translate("TabWidget", "000. 000. 000. 000;_"))
        self.localipLineEdit.setText(_translate("TabWidget", ". . . "))
        self.localipAutoCheckBox.setText(_translate("TabWidget", "自动分配"))
        self.connectionPushButton.setText(_translate("TabWidget", "连接"))
        self.connectionMsgTextBrowser.setHtml(_translate("TabWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Text</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">123</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">test</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">你好</p></body></html>"))
        TabWidget.setTabText(TabWidget.indexOf(self.mainTab), _translate("TabWidget", "主页"))
